project:
  type: website
  output-dir: docs

website:
  title: "Joyce X"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - href: Joyce_Xuan_Resume.pdf
        text: CV

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

